name: Run Cypress Tests
on:
  schedule:
    - cron: "*/5 * * * *" #run every 2 hour 40 mins

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Hourly Run
        run: npx cypress run --spec "**/Login.spec.cy.js" --record --key aac4cc8e-6b7a-48b3-b520-a5cef98c1a84
